stages:
  - lint
  - dialyzer
  - eunit

lint:
  stage: lint
  script:
    - ./rebar3 as lint lint
  tags:
    - erlagn-19

dialyzer:
  stage: dialyzer
  script:
    - ./rebar3 dialyzer
  tags:
    - erlagn-19

eunit:
  stage: eunit
  script:
    - ./rebar3 eunit
  tags:
    - erlagn-19
